import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?display=swap&family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=add_location_alt,admin_panel_settings,arrow_back_ios_new,close,error,logout,my_location,open_in_new,travel_explore,unpaved_road" />
      </head>
      <body
        className={`bg-purple-100`}
      >
        {children}
      </body>
    </html>
  );
}
